In [2]:
import numpy as np
arr=np.random.randn(5,4)
arr.mean()
#算所有数的平均值


-0.11090263755197208

In [3]:
arr.sum()#所有数的和

-2.2180527510394414

In [4]:
arr

array([[ 1.16132492,  1.62527545,  1.3040154 ,  0.53833074],
       [-0.61417926, -1.39956193, -0.91304427, -0.14870202],
       [ 0.87176837,  0.12548843, -1.74035089, -1.73434909],
       [ 0.11148291,  0.2404562 , -0.15277656, -2.17903662],
       [ 1.09151995, -0.24661741,  1.30547904, -1.46457613]])

In [5]:
arr.mean(axis=0)#0表示按行取出来每一行的第一个元素各自加起来除以有几行这样的，其实就有点像列了,就是反过来是计算列的平均值

array([ 0.52438338,  0.06900815, -0.03933545, -0.99766662])

In [6]:
arr.mean(1)#计算每一行的平均值

array([ 1.15723663, -0.76887187, -0.61936079, -0.49496852,  0.17145136])

In [7]:
arr.sum(0)#计算每一列的和

array([ 2.62191689,  0.34504074, -0.19667727, -4.98833312])

In [8]:
arr.cumsum(0)#所有列的累积和，返回同样大小的数组


array([[ 1.16132492,  1.62527545,  1.3040154 ,  0.53833074],
       [ 0.54714567,  0.22571352,  0.39097114,  0.38962872],
       [ 1.41891404,  0.35120195, -1.34937975, -1.34472037],
       [ 1.53039695,  0.59165815, -1.50215631, -3.52375699],
       [ 2.62191689,  0.34504074, -0.19667727, -4.98833312]])

In [9]:
arr.cumprod(1)#所有行的累成积

array([[ 1.16132492,  1.88747289,  2.46129372,  1.32499008],
       [-0.61417926,  0.85958191, -0.78483633,  0.11670675],
       [ 0.87176837,  0.10939684, -0.1903889 ,  0.33020081],
       [ 0.11148291,  0.02680676, -0.00409544,  0.00892412],
       [ 1.09151995, -0.26918782, -0.35141906,  0.51467996]])

In [11]:
arr=np.random.randn(100)
arr>0#返回一个bool矩阵，这个本质上里面都是0，1，所以可以用来算满足条件的个数

array([ True,  True, False,  True, False, False,  True, False, False,
        True, False,  True,  True, False, False,  True,  True,  True,
       False, False,  True, False, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False,  True,  True, False, False,  True,  True,  True,
       False, False,  True, False, False, False, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False, False,  True, False,  True,  True,  True,
       False])

In [12]:
(arr>0).sum()

48

In [13]:
bools=np.array([False,True])
bools.any()#是否有一个或多个true

True

In [14]:
bools.all()#是否都是true

False

In [15]:
arr=np.random.randn(5,3)
arr

array([[ 0.64801203, -1.8564877 , -2.79036139],
       [ 0.54535194, -1.52008249, -1.66388801],
       [-0.7140252 , -0.31821152,  0.1516694 ],
       [-0.92060456,  0.17047779, -0.88845731],
       [ 1.54952424,  2.63742852,  0.6221507 ]])

In [17]:
arr.sort(0)#按列排序
arr

array([[-0.92060456, -1.8564877 , -2.79036139],
       [-0.7140252 , -1.52008249, -1.66388801],
       [ 0.54535194, -0.31821152, -0.88845731],
       [ 0.64801203,  0.17047779,  0.1516694 ],
       [ 1.54952424,  2.63742852,  0.6221507 ]])

In [18]:
arr.sort(1)#按行排序，在对多维数组进行操作的时候刚好行列传进去都是反过来的
arr

array([[-2.79036139, -1.8564877 , -0.92060456],
       [-1.66388801, -1.52008249, -0.7140252 ],
       [-0.88845731, -0.31821152,  0.54535194],
       [ 0.1516694 ,  0.17047779,  0.64801203],
       [ 0.6221507 ,  1.54952424,  2.63742852]])

In [19]:
names=np.array(['a','a','b','c','c'])
np.unique(names)#返回唯一值并排序有点像set

array(['a', 'b', 'c'], dtype='<U1')

In [20]:
x=np.array([1,1,1,2])
y=np.array([2])
np.in1d(x,y)#返回x中的各个元素在不在y中的数组里面

array([False, False, False,  True])

In [23]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
from numpy import linalg as a
x=np.random.randn(2,2)
a.qr(np.random.randn(2,2))#返回qr分解

(array([[-0.72523525,  0.68850115],
        [ 0.68850115,  0.72523525]]), array([[ 1.11037365, -0.17200612],
        [ 0.        ,  2.4271787 ]]))

In [32]:
a.inv(x)#求逆

array([[ 0.50624936,  0.21343841],
       [ 0.21459955, -0.34778403]])

In [33]:
y=np.random.randn(2,2)
a.solve(x,y)#求xA=y A的值


array([[-1.16981651,  0.97952889],
       [-0.5364938 ,  0.38615095]])

In [34]:
a.eig(x)#计算特征向量

(array([ 1.79571879, -2.50994727]), array([[ 0.97299894, -0.22962674],
        [ 0.23080958,  0.97327877]]))

In [37]:
arr=np.random.normal(2,3)
arr

0.4266989797806966

In [39]:
arr=np.random.normal(size=(2,3))#np的rand更加强大可以随机生成一些成标准正太分布的数据，或者其他各种分布的数据，这些都叫做伪随机数
arr

array([[ 0.02596   , -0.15217129, -0.75190436],
       [-0.10341459,  1.10940019, -0.00124745]])

In [46]:
#随机漫步的过程
nsteps=1000
draws=np.random.randint(0,2,size=nsteps)#生成一个有1000个元素的一维数组
steps=np.where(draws>0,1,-1)



In [47]:
steps

array([ 1, -1, -1,  1, -1, -1, -1,  1,  1, -1, -1, -1,  1,  1,  1, -1,  1,
       -1,  1, -1,  1, -1, -1, -1,  1,  1, -1,  1, -1, -1,  1, -1,  1, -1,
       -1,  1,  1, -1,  1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1, -1,  1,
       -1,  1, -1,  1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1,
        1, -1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1,  1,
       -1,  1,  1, -1, -1, -1, -1, -1,  1, -1,  1, -1,  1,  1,  1, -1, -1,
       -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1,  1, -1,  1, -1, -1,
        1, -1, -1,  1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1, -1,  1,  1,
        1,  1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1, -1,
       -1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1,
        1,  1, -1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1,  1,  1,  1,
       -1, -1,  1,  1, -1,  1, -1, -1,  1, -1,  1,  1, -1,  1, -1,  1,  1,
        1,  1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1,  1,  1, -1,
        1,  1, -1, -1, -1

In [48]:
walk=steps.cumsum()#累加

In [49]:
walk

array([  1,   0,  -1,   0,  -1,  -2,  -3,  -2,  -1,  -2,  -3,  -4,  -3,
        -2,  -1,  -2,  -1,  -2,  -1,  -2,  -1,  -2,  -3,  -4,  -3,  -2,
        -3,  -2,  -3,  -4,  -3,  -4,  -3,  -4,  -5,  -4,  -3,  -4,  -3,
        -4,  -3,  -4,  -5,  -4,  -5,  -6,  -7,  -6,  -5,  -6,  -5,  -6,
        -5,  -6,  -5,  -6,  -7,  -6,  -5,  -6,  -7,  -8,  -9, -10, -11,
       -10, -11, -12, -11, -12, -11, -12, -11, -10,  -9, -10,  -9,  -8,
        -7,  -8,  -7,  -6,  -5,  -6,  -5,  -6,  -5,  -4,  -5,  -6,  -7,
        -8,  -9,  -8,  -9,  -8,  -9,  -8,  -7,  -6,  -7,  -8,  -9,  -8,
        -7,  -6,  -5,  -6,  -7,  -8,  -7,  -6,  -5,  -6,  -5,  -6,  -5,
        -6,  -7,  -6,  -7,  -8,  -7,  -8,  -7,  -6,  -7,  -8,  -9,  -8,
        -7,  -6,  -5,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   0,  -1,
        -2,  -3,  -4,  -3,  -2,  -1,   0,  -1,   0,  -1,  -2,  -1,   0,
         1,   2,   1,   0,   1,   0,   1,   0,   1,   2,   3,   2,   3,
         4,   5,   6,   5,   4,   5,   4,   3,   4,   5,   6,   

In [50]:
walk.max()

30

In [51]:
walk.min()

-12

In [52]:
(np.abs(walk)>=10).argmax()#第一个大于10的索引

63