In [2]:
a=[[1,2,3,4],[5,6,7,8]]
import numpy as np
x=np.array(a)
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
x.flatten()#压缩成一维数组

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
import os 
# path1=os.path.join(os.getcwd(),"desktop")
# path2=os.path.join(path1,"automate_online-materials")
# path3=os.path.join(path2,"example.csv")
y=np.loadtxt('output.csv',dtype=np.int,delimiter=',')#delimiter 是分隔符，usecols指定的列，但有些问题,
#unpack 为true的话就会将每个属性作为不同的数组,false 就是默认一个数组

In [49]:
print(y)#Csv文件里面的数据要用逗号隔开才可以全部读入进来

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
y.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [51]:
k=y.reshape(2,6)

In [52]:
k

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [53]:
temp=np.delete(k,0,axis=0)#0代表对行进行操作，1代表对列进行操作，2 代表对高

In [54]:
temp.tolist()

[[7, 8, 9, 10, 11, 12]]

In [55]:
temp=np.delete(k,0,axis=1)

In [56]:
temp.tolist()

[[2, 3, 4, 5, 6], [8, 9, 10, 11, 12]]

In [7]:
np.empty((2,6))#返回的都是一些随意的垃圾值，它只用来创建新数组，分配内存空间，不填充任何值

array([[1.31660879e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000, 8.99285626e+218, 2.12650544e+160],
       [2.95143131e+179, 1.74451157e-076, 2.52667916e-052,
        2.77123850e-057, 2.02018453e-076, 1.33712395e+165]])

In [12]:
np.eye(2,4)#单位矩阵

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
m=np.identity(4)#identity 创建的是方阵

In [21]:
m[:2]=4#切片出来会发生变化，如果要不影响回来的话要先m[:2].copy()

In [22]:
m

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
m[:2,1:]#逗号隔开，表示取前两行，取第一列除外的列

array([[4., 4., 4.],
       [4., 4., 4.]])

In [26]:
m[1,2]

4.0

In [27]:
m[1][2]#等价

4.0

In [28]:
m[3]

array([0., 0., 0., 1.])

In [29]:
m[3,1:]#二维数组的选取子矩阵的方式

array([0., 0., 1.])

In [34]:
char=np.array(['a','b','c'])#u1应该是字符串的长度

In [35]:
char=='a'#会显示bool矩阵，而且可以作为数组的下标索引返回，比如‘a’的下标就是

array([ True, False, False])

In [36]:
char[char=='a']#返回的还是数组

array(['a'], dtype='<U1')

In [41]:
char[(char=='a')|(char=='c')]#用&和|来表示and ,or

array(['a', 'c'], dtype='<U1')

In [49]:
data=np.empty((2,6))

In [50]:
data

array([[1.31660879e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000, 8.99285626e+218, 2.12650544e+160],
       [2.95143131e+179, 1.74451157e-076, 2.52667916e-052,
        2.77123850e-057, 2.02018453e-076, 1.33712395e+165]])

In [51]:
data[data>0]=0

In [52]:
data

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [53]:
data=np.array([1,2,3,4,-1,3,-5])

In [54]:
data[data<0]=0#可以用来修改里面的值

In [55]:
data

array([1, 2, 3, 4, 0, 3, 0])

In [57]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i

In [58]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [59]:
arr[[4,3,0,6]]#花式索引，把你要取出来的行以列表的形式传入进去


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [60]:
arr[[-3,-5,-7]]#加了负数的话就从末行返回去数

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [62]:
arr=np.arange(32).reshape((8,4))

In [63]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [64]:
arr[[1,5,7,2],[0,3,1,2]]#会选出（1，0），（5，3）...这些元素来放到一个列表里

array([ 4, 23, 29, 10])

In [66]:
arr=np.arange(15).reshape((3,5))
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr.T#转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [68]:
arr=np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [69]:
arr.transpose((1,0,2))#高维的数据转置需要用transpose 传入参数，这边表示1,0这两个轴位置交换了

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [70]:
x=np.random.randn(8)#随机生成一些成正太分布的随机值
y=np.random.randn(8)
x

array([-0.77216726,  0.54389143,  0.26091397, -0.75766557,  0.55690613,
       -1.39765276, -0.38967909, -0.14185837])

In [71]:
y

array([ 1.58652245e-02, -1.03279956e-03, -1.45911896e-01,  1.80722686e+00,
        7.74047966e-01, -5.19459317e-01,  3.90138905e-01, -1.24009617e+00])

# 元素级别（单单对元素进行处理的）通用函数

In [72]:
np.sqrt(x)

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 0.73748995, 0.51079739,        nan, 0.74626144,
              nan,        nan,        nan])

In [73]:
np.exp(x)

array([0.46201069, 1.72269759, 1.29811599, 0.46875944, 1.74526452,
       0.24717647, 0.67727418, 0.86774414])

In [74]:
np.maximum(x,y)#会把两个数组每个位置的元素一一对应起来选出大的出来

array([ 0.01586522,  0.54389143,  0.26091397,  1.80722686,  0.77404797,
       -0.51945932,  0.3901389 , -0.14185837])

In [75]:
arr=np.random.randn(7)*5

In [76]:
arr

array([-10.11249627,   3.22665576,   7.12459255,   5.25854117,
         6.96547986,   2.9224464 ,   4.76124554])

In [77]:
remainder,whole_part=np.modf(arr)#modf可以把小数部分和整数部分分开来

In [78]:
remainder

array([-0.11249627,  0.22665576,  0.12459255,  0.25854117,  0.96547986,
        0.9224464 ,  0.76124554])

In [79]:
whole_part

array([-10.,   3.,   7.,   5.,   6.,   2.,   4.])

In [82]:
import glob
glob.glob('*.csv')#这个也可以用os 模块里的listdir把文件全部列出来，再遍历一下，看有没有endswith('.py')的

['output.csv']

In [83]:
import sys
print(sys.argv)#可以查看运行这个文件的命令行信息

['C:\\Users\\admin\\Anaconda3\\lib\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\admin\\AppData\\Roaming\\jupyter\\runtime\\kernel-9cab74c1-916c-4a85-90a7-8f67bd9ca643.json']


In [84]:
from datetime import date
now=date.today()

In [85]:
now

datetime.date(2020, 3, 21)

In [87]:
birthday=date(2000,5,8)
age=now-birthday
age.days#可以算自己活了多少天啊哈哈

7257

In [88]:
import os
os.listdir()

['.anaconda',
 '.astropy',
 '.bash_history',
 '.conda',
 '.condarc',
 '.config',
 '.gitconfig',
 '.idea',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.node_repl_history',
 '.npmrc',
 '.PyCharm2019.2',
 '.pylint.d',
 '.ssh',
 '.vscode',
 '3D Objects',
 'Anaconda3',
 'AppData',
 'Application Data',
 'bigdata.ipynb',
 'Contacts',
 'Cookies',
 'csv.ipynb',
 'Desktop',
 'df_orig.pkl',
 'Documents',
 'Downloads',
 'excel.ipynb',
 'Favorites',
 'Fonts',
 'Funshion',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'MPlugin.dll',
 'Music',
 'My Documents',
 'mysql',
 'mysql-5.7.29-winx64.zip',
 'NetHood',
 'node-v12.15.0-x64.msi',
 'nodejs',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{f057e6e1-c4ec-11e9-aedc-eee6157f1e4d}.TM.blf',
 'NTUSER.DAT{f057e6e1-c4ec-11e9-aedc-eee6157f1e4d}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{f057e6e1-c4ec-11e9-aedc-eee6157f1e4d}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Num

In [91]:
for i in os.listdir():
    if i.endswith('.ipynb'):
        
        print(i,)

bigdata.ipynb
csv.ipynb
excel.ipynb
Numpy.ipynb
part1-data finished.ipynb
part1-data.ipynb
part2-model finished.ipynb
part2-model.ipynb
part3-serving.ipynb
part4-evaluation finished.ipynb
unconstrained-demo.ipynb
辅导一.ipynb


In [92]:
a=os.getcwd()
b=os.path.join(a,"desktop")
c=os.path.join()
#os.mkdir('')

'C:\\Users\\admin\\desktop'

In [8]:
from datetime import date
import datetime
birthday=date(1777,4,30)
now=date(1791,12,15)
age=now-birthday
age.days#可以算自己活了多少天啊哈哈

5342

In [10]:
time=datetime.timedelta(days=8112)
y=birthday+time
print(y)

1799-07-16


In [11]:
#zip的一些用法
a=["a",'b','c']
b=['d','e','f']
pack=zip(a,b)#生成器只会生成一次
print(list(pack))
print(tuple(pack))
print(dict(pack))

[('a', 'd'), ('b', 'e'), ('c', 'f')]
()
{}


In [12]:
pack=zip(a,b)
print(tuple(pack))

(('a', 'd'), ('b', 'e'), ('c', 'f'))


In [13]:
pack=zip(a,b)
print(dict(pack))

{'a': 'd', 'b': 'e', 'c': 'f'}


In [14]:
for i,j in zip(a,b):
    print(i,j)

a d
b e
c f


In [18]:
#python的表达式 x if c else y 表示c是true 就是x,否则是y,np.where可以快速写这个功能
import numpy as np
a=np.arange(5)
b=np.arange(6,11)
c=np.array([1,0,1,0,1],dtype=bool)
result=np.where(c,a,b)#a if c else b,也可以用来替换矩阵的值之类的
print(result)

[0 7 2 9 4]
